#!/bin/bash

pdir=$PASSWORD_STORE_DIR
if [ -z "$var" ]
then
    pdir="$HOME/.spm"
fi

pass_input=`find $pdir -type d \( -path ./.git -o -path ./log -o -path ./public -o -path ./tmp \) -prune -o -print | \
    xargs -0 -i bash -c 'if [ ! -d "{}" ]; then echo "{}"; fi' | \
    grep -i ".gpg$" | \
    sed 's/.gpg$//g' | \
    sed "s~$pdir/~~g" | \
    mdmenu -nb \#272822 -nf \#F6F6F6 -sb \#47196D -sf \#F6F6F6 -mc \#1E1F1C \
           -topof 22 -winpad 2 -texthpad 5 -textvpad 3   \
           -mainfn "DejaVu Sans Mono-15" -dmenu`

[[ -n $pass_input ]] || exit

spm show $pass_input | xclip -sel clip
